ALTER TABLE "PLANNING_TOOL"."ALLOCATION_CATEGORY" ADD (SINGLE_OPTION_ONLY TINYINT NOT NULL DEFAULT 0);

UPDATE "PLANNING_TOOL"."ALLOCATION_CATEGORY"
SET SINGLE_OPTION_ONLY = 1
WHERE NAME LIKE '%Buying Classification%';

INSERT INTO "PLANNING_TOOL"."ALLOCATION_OPTION" (NAME, CREATED_USER_ID)
VALUES ('All', 1);

INSERT INTO "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL" (ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, IN_PROCESSING_REPORT, CREATED_USER_ID)
VALUES ((SELECT ALLOCATION_CATEGORY_ID FROM "PLANNING_TOOL"."ALLOCATION_CATEGORY"
WHERE NAME LIKE '%Buying Classification%'), (SELECT ALLOCATION_OPTION_ID FROM "PLANNING_TOOL"."ALLOCATION_OPTION"
WHERE NAME LIKE 'All'), 2, 1, 1);

INSERT INTO "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL" (ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, IN_PROCESSING_REPORT, CREATED_USER_ID)
VALUES ((SELECT ALLOCATION_CATEGORY_ID FROM "PLANNING_TOOL"."ALLOCATION_CATEGORY"
WHERE NAME LIKE '%Buying Classification%'), (SELECT ALLOCATION_OPTION_ID FROM "PLANNING_TOOL"."ALLOCATION_OPTION"
WHERE NAME LIKE 'All'), 3, 1, 1);
-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-58', 'Alocation Category Support Single Option', 'V201708291300__Alocation_Category_Support_Single_Option.sql');

COMMIT;