CREATE PROCEDURE "PLANNING_TOOL"."xsplanningtool.db.procedures::INS_EXPECTED_OUTCOME_OPTION_IF_NOT_EXISTS" (

--CATEGORY PARAMETERS
	IN in_alias NVARCHAR(255),
	IN in_name NVARCHAR(255)
)
	LANGUAGE SQLSCRIPT
	SQL SECURITY INVOKER

	AS
BEGIN
	DECLARE OUT_COUNT_EXPECTED_OUTCOME INT;
	DECLARE OUT_EXPECTED_OUTCOME_OPTION_ID BIGINT;
   	DECLARE OUT_EXPECTED_OUTCOME_ID BIGINT;


	SELECT COUNT(C.EXPECTED_OUTCOME_OPTION_ID) INTO OUT_COUNT_EXPECTED_OUTCOME FROM "PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION" C WHERE UPPER(C.NAME) = UPPER(in_name);


	IF OUT_COUNT_EXPECTED_OUTCOME > 0
	THEN
		UPDATE "PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"
		SET CSV_ALIAS = in_alias
		WHERE UPPER(NAME) = UPPER(in_name);
	ELSE
		insert into "PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION"(NAME, CREATED_USER_ID, CSV_ALIAS) values(in_name, 1, in_alias);
		SELECT C.EXPECTED_OUTCOME_OPTION_ID INTO OUT_EXPECTED_OUTCOME_OPTION_ID FROM "PLANNING_TOOL"."EXPECTED_OUTCOME_OPTION" C WHERE UPPER(C.NAME) = UPPER(in_name);
		SELECT EO.EXPECTED_OUTCOME_ID INTO OUT_EXPECTED_OUTCOME_ID FROM "PLANNING_TOOL"."EXPECTED_OUTCOME" EO WHERE UPPER(EO.NAME) = UPPER('Campaign Forecasting');
		insert into "PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL"(HIERARCHY_LEVEL_ID, EXPECTED_OUTCOME_ID,EXPECTED_OUTCOME_OPTION_ID, CREATED_USER_ID) values(2, :OUT_EXPECTED_OUTCOME_ID, :OUT_EXPECTED_OUTCOME_OPTION_ID, 1);
		insert into "PLANNING_TOOL"."EXPECTED_OUTCOME_LEVEL"(HIERARCHY_LEVEL_ID, EXPECTED_OUTCOME_ID,EXPECTED_OUTCOME_OPTION_ID, CREATED_USER_ID) values(3, :OUT_EXPECTED_OUTCOME_ID, :OUT_EXPECTED_OUTCOME_OPTION_ID, 1);
	END IF;
END;


--insert new expected outcome option
call "PLANNING_TOOL"."xsplanningtool.db.procedures::INS_EXPECTED_OUTCOME_OPTION_IF_NOT_EXISTS"('MGO volume', 'Expected MNP Volume');
call "PLANNING_TOOL"."xsplanningtool.db.procedures::INS_EXPECTED_OUTCOME_OPTION_IF_NOT_EXISTS"('MGO value', 'Expected MNP Value');
--call "PLANNING_TOOL"."xsplanningtool.db.procedures::INS_EXPECTED_OUTCOME_OPTION_IF_NOT_EXISTS"('Expected  Lead Volume',null);


DROP PROCEDURE "PLANNING_TOOL"."xsplanningtool.db.procedures::INS_EXPECTED_OUTCOME_OPTION_IF_NOT_EXISTS";

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-32', 'New KPI Options', 'V201703201300__New_KPI_Options.sql');

COMMIT;