--set available true all permission for superadmin role
update "PLANNING_TOOL"."ROLE_PERMISSION"
set deleted = 0, enabled = 1
where role_id = 1;


INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,9,9,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,9,10,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,9,11,1);

INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,10,9,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,10,10,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION"(ROLE_ID,RESOURCE_ID,PERMISSION_ID, CREATED_USER_ID) VALUES(1,11,11,1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-36', 'Update to enabled all permissions for SuperAdmin Role', 'V201704130900__UpdateSuperAdmin_RolePermission.sql');

COMMIT;