ALTER TABLE "PLANNING_TOOL"."HL4_PARTNER" ADD ("VALUE_AUX" DECIMAL(19,6));

UPDATE "PLANNING_TOOL"."HL4_PARTNER"
SET VALUE_AUX = VALUE;

RENAME COLUMN "PLANNING_TOOL"."HL4_PARTNER"."VALUE" TO "VALUE_BKP";

RENAME COLUMN "PLANNING_TOOL"."HL4_PARTNER"."VALUE_AUX" TO "VALUE";

ALTER TABLE "PLANNING_TOOL"."HL4_PARTNER" DROP ("VALUE_BKP");

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-33', 'Change DataType Presicion', 'V201704070920__ChangeDataType_Presicion');

COMMIT;