insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 4, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 8, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 9, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 11, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 12, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 14, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 15, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 16, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 17, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 20, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 21, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 22, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 23, 2, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 29, 2, 1);

insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 4, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 8, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 9, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 11, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 12, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 14, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 15, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 16, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 17, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 20, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 21, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 22, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 23, 3, 1);
insert into "PLANNING_TOOL"."ALLOCATION_CATEGORY_OPTION_LEVEL"( ALLOCATION_CATEGORY_ID, ALLOCATION_OPTION_ID, HIERARCHY_LEVEL_ID, CREATED_USER_ID) values( 7, 29, 3, 1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-24', 'Extend Initial data for category and options', 'V201702091650__Extend_Initial_Category_Option_ByLevel.sql');

COMMIT;
