ALTER TABLE "PLANNING_TOOL"."HL1_USER" ADD ("HL1_USER_ID" bigint null generated by default as IDENTITY);

ALTER TABLE "PLANNING_TOOL"."HL1_USER" ADD PRIMARY KEY ("HL1_USER_ID");

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-28', 'Fix Migration L1 Table', 'V201703061130__Hl1_User_Update.sql');

COMMIT;

