-------------------------------------------- HL5 --------------------------------------------

CREATE COLUMN TABLE "PLANNING_TOOL"."DISTRIBUTION_CHANNEL" (
	DISTRIBUTION_CHANNEL_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_STATUS_DETAIL" (
        HL5_STATUS_DETAIL_ID bigint not null primary key generated by default as IDENTITY,
        DETAIL NVARCHAR(255) NOT NULL ,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")        
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL5"(
        HL5_ID bigint not null primary key generated by default as IDENTITY,
        hl5_crm_description nvarchar(100) not null,
        acronym nvarchar(25) not null,
        DISTRIBUTION_CHANNEL_ID BIGINT NOT NULL,
        BUDGET DECIMAL(19,2) NOT NULL,
		HL4_ID BIGINT NOT NULL,
        CAMPAIGN_OBJECTIVE_ID BIGINT,
        CAMPAIGN_TYPE_ID BIGINT,
        CAMPAIGN_SUBTYPE_ID BIGINT,
        MARKETING_PROGRAM_ID BIGINT,
        MARKETING_ACTIVITY_ID BIGINT,
        ACTUAL_START_DATE timestamp,
        ACTUAL_END_DATE timestamp,
        SHOW_ON_DG_CALENDAR TINYINT DEFAULT 0,
        BUSINESS_OWNER_ID BIGINT,
		EMPLOYEE_RESPONSIBLE_ID BIGINT,
        COST_CENTER_ID BIGINT,
        in_budget tinyint not null, -- 1 = in budget, 0 = out of budget
        budget_spend_q1 decimal(19,2) not null,
        budget_spend_q2 decimal(19,2) not null,
        budget_spend_q3 decimal(19,2) not null,
        budget_spend_q4 decimal(19,2) not null,
        euro_conversion_id bigint not null,
        hl5_status_detail_id bigint not null,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL4_ID") REFERENCES "PLANNING_TOOL"."HL4"("HL4_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("EURO_CONVERSION_ID") REFERENCES "PLANNING_TOOL"."EURO_CONVERSIONS"("EURO_CONVERSION_ID"),
        FOREIGN KEY ("HL5_STATUS_DETAIL_ID") REFERENCES "PLANNING_TOOL"."HL5_STATUS_DETAIL"("HL5_STATUS_DETAIL_ID"),
        FOREIGN KEY ("DISTRIBUTION_CHANNEL_ID") REFERENCES "PLANNING_TOOL"."DISTRIBUTION_CHANNEL"("DISTRIBUTION_CHANNEL_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_BUDGET"(
        hl5_budget_id  bigint not null primary key generated by default as IDENTITY,
        HL5_ID bigint not null,
		organization_id bigint, --not be null
        percentage decimal(19,2), --TODO: set not null
        organization_type tinyint not null, -- 1 = regional, 2 = central
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_SALES"(
        hl5_sales_id bigint not null primary key generated by default as IDENTITY,
        HL5_ID bigint not null,
        organization_id bigint, --can be null
        amount decimal(19,2), --todo: ca not be null
        organization_type tinyint not null, -- 1 = regional, 2 = central, 3 = other
        description nvarchar(255),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),       
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID") 
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_PARTNER" (
        PARTNER_ID bigint not null primary key generated by default as IDENTITY,
        PARTNER_NAME NVARCHAR(512) NOT NULL ,
        PARTNER_TYPE_ID BIGINT NOT NULL ,
        HL5_ID BIGINT NOT NULL ,
        REGION_ID BIGINT NOT NULL ,
        VALUE DECIMAL(19,2) NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),       
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("REGION_ID") REFERENCES "PLANNING_TOOL"."REGION"("REGION_ID"),      
        FOREIGN KEY ("PARTNER_TYPE_ID") REFERENCES "PLANNING_TOOL"."PARTNER_TYPE"("PARTNER_TYPE_ID")        
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_EXPECTED_OUTCOMES" (
        HL5_EXPECTED_OUTCOMES_ID bigint not null primary key generated by default as IDENTITY,
        HL5_ID BIGINT NOT NULL ,
        COMMENTS NVARCHAR(3000),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),       
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")        
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_EXPECTED_OUTCOMES_DETAIL" (
        HL5_EXPECTED_OUTCOMES_DETAILS_ID bigint not null primary key generated by default as IDENTITY,
        HL5_EXPECTED_OUTCOMES_ID BIGINT NOT NULL,
        OUTCOMES_ID BIGINT NOT NULL,
        EURO_VALUE DECIMAL(19,2) DEFAULT 0 NOT NULL,
        VOLUME_VALUE DECIMAL(19,2) DEFAULT 0 NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_EXPECTED_OUTCOMES_ID") REFERENCES "PLANNING_TOOL"."HL5_EXPECTED_OUTCOMES"("HL5_EXPECTED_OUTCOMES_ID"),       
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("OUTCOMES_ID") REFERENCES "PLANNING_TOOL"."OUTCOMES"("OUTCOMES_ID")        
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_CATEGORY" (
        HL5_CATEGORY_ID  bigint not null primary key generated by default as IDENTITY,
        HL5_ID BIGINT NOT NULL,
        CATEGORY_ID BIGINT NOT NULL,
        IN_PROCESSING_REPORT TINYINT DEFAULT 0,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("CATEGORY_ID") REFERENCES "PLANNING_TOOL"."CATEGORY"("CATEGORY_ID")                
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_CATEGORY_OPTION" (
        HL5_CATEGORY_OPTION_ID bigint not null primary key generated by default as IDENTITY,
        HL5_CATEGORY_ID BIGINT NOT NULL,
        OPTION_ID BIGINT NOT NULL,
        AMOUNT DECIMAL(19,2) NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_CATEGORY_ID") REFERENCES "PLANNING_TOOL"."HL5_CATEGORY"("HL5_CATEGORY_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("OPTION_ID") REFERENCES "PLANNING_TOOL"."OPTION"("OPTION_ID")                        
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_CRM_BINDING" (
        HL5_CRM_BINDING_ID bigint not null primary key generated by default as IDENTITY,
        HL5_ID BIGINT NOT NULL,
        COLUMN_NAME NVARCHAR(255) NOT NULL ,
        COLUMN_CHANGED TINYINT  DEFAULT 1 NOT NULL,
        display_name nvarchar(255),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_STATUS_HISTORY" (
        HL5_STATUS_HISTORY_ID bigint not null primary key generated by default as IDENTITY,
        HL5_STATUS_DETAIL_ID BIGINT NOT NULL ,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        created_user_id bigint not null,
        HL5_ID BIGINT NOT NULL,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),        
        FOREIGN KEY ("HL5_STATUS_DETAIL_ID") REFERENCES "PLANNING_TOOL"."HL5_STATUS_DETAIL"("HL5_STATUS_DETAIL_ID")          
);


/* Soporte extendido para team global - L5*/
CREATE COLUMN TABLE "PLANNING_TOOL"."HL5_IPS"(
        hl5_ips_id  bigint not null primary key generated by default as IDENTITY,
        HL5_ID bigint not null,
        --ips_id  bigint not null, --TODO: FK to ???
		ips_id  bigint,
        percentage decimal(19,2),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);


-------------------------------------------- HL5 --------------------------------------------
-------------------------------------------- HL6 --------------------------------------------

/* Primer release L5/L6 - funcionalidades minimas */
CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_STATUS_DETAIL" (
        HL6_STATUS_DETAIL_ID bigint not null primary key generated by default as IDENTITY,
        DETAIL NVARCHAR(255) NOT NULL ,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")                
);

CREATE COLUMN TABLE "PLANNING_TOOL"."ROUTE_TO_MARKET" (
	ROUTE_TO_MARKET_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."SALE_ORGANIZATION" (
	SALES_ORGANIZATION_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL6"(
        HL6_ID bigint not null primary key generated by default as IDENTITY,
        HL6_crm_description nvarchar(100) not null,
        acronym nvarchar(25) not null,
        BUDGET DECIMAL(19,2) NOT NULL,
		HL5_ID BIGINT NOT NULL,
		ROUTE_TO_MARKET_ID BIGINT NOT NULL,
		CAMPAIGN_OBJECTIVE_ID BIGINT,
        CAMPAIGN_TYPE_ID BIGINT,
        CAMPAIGN_SUBTYPE_ID BIGINT,
        MARKETING_PROGRAM_ID BIGINT,
        MARKETING_ACTIVITY_ID BIGINT,
        ACTUAL_START_DATE timestamp,
        ACTUAL_END_DATE timestamp,
        SHOW_ON_DG_CALENDAR TINYINT DEFAULT 0,
        BUSINESS_OWNER_ID BIGINT,
		EMPLOYEE_RESPONSIBLE_ID BIGINT,
        COST_CENTER_ID BIGINT,
        in_budget tinyint not null, -- 1 = in budget, 0 = out of budget
        budget_spend_q1 decimal(19,2) not null,
        budget_spend_q2 decimal(19,2) not null,
        budget_spend_q3 decimal(19,2) not null,
        budget_spend_q4 decimal(19,2) not null,
        euro_conversion_id bigint not null,
        hl6_status_detail_id bigint not null,
        SALES_ORGANIZATION_ID BIGINT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL5_ID") REFERENCES "PLANNING_TOOL"."HL5"("HL5_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),        
        FOREIGN KEY ("EURO_CONVERSION_ID") REFERENCES "PLANNING_TOOL"."EURO_CONVERSIONS"("EURO_CONVERSION_ID"),        
        FOREIGN KEY ("HL6_STATUS_DETAIL_ID") REFERENCES "PLANNING_TOOL"."HL6_STATUS_DETAIL"("HL6_STATUS_DETAIL_ID"),
		FOREIGN KEY ("ROUTE_TO_MARKET_ID") REFERENCES "PLANNING_TOOL"."ROUTE_TO_MARKET"("ROUTE_TO_MARKET_ID"),
		FOREIGN KEY ("SALES_ORGANIZATION_ID") REFERENCES "PLANNING_TOOL"."SALE_ORGANIZATION"("SALES_ORGANIZATION_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_BUDGET"(
        hl6_budget_id  bigint not null primary key generated by default as IDENTITY,
        HL6_ID bigint not null,
		organization_id bigint,
        percentage decimal(19,2),
        organization_type tinyint not null, -- 1 = regional, 2 = central
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);


CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_SALES"(
        hl6_sales_id bigint not null primary key generated by default as IDENTITY,
        HL6_ID bigint not null,
        --organization_id bigint not null, --TODO: FK of ???
		organization_id bigint,
        amount decimal(19,2),
        organization_type tinyint not null, -- 1 = regional, 2 = central, 3 = other
        description nvarchar(255),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")        
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_PARTNER" (
        HL6_PARTNER_ID bigint not null primary key generated by default as IDENTITY,
        PARTNER_NAME NVARCHAR(512) NOT NULL ,
        PARTNER_TYPE_ID BIGINT NOT NULL ,
        HL6_ID BIGINT NOT NULL,
        REGION_ID BIGINT NOT NULL ,
        VALUE DECIMAL(19,2) NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("PARTNER_TYPE_ID") REFERENCES "PLANNING_TOOL"."PARTNER_TYPE"("PARTNER_TYPE_ID"),                  
        FOREIGN KEY ("REGION_ID") REFERENCES "PLANNING_TOOL"."REGION"("REGION_ID")        
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_CRM_BINDING" (
        HL6_CRM_BINDING_ID bigint not null primary key generated by default as IDENTITY,
        HL6_ID BIGINT NOT NULL,
        COLUMN_NAME NVARCHAR(255) NOT NULL ,
        COLUMN_CHANGED TINYINT  DEFAULT 1 NOT NULL,
        display_name nvarchar(255),
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")        
);

CREATE COLUMN TABLE "PLANNING_TOOL"."HL6_STATUS_HISTORY" (
        HL6_STATUS_HISTORY_ID bigint not null primary key generated by default as IDENTITY,
        HL6_STATUS_DETAIL_ID BIGINT NOT NULL ,
		HL6_ID BIGINT NOT NULL,
        created_date_tz timestamp default CURRENT_TIMESTAMP,
        created_user_id bigint not null,
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID"),        
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL6_STATUS_DETAIL_ID") REFERENCES "PLANNING_TOOL"."HL6_STATUS_DETAIL"("HL6_STATUS_DETAIL_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."COST_CENTER" (
		COST_CENTER_ID bigint not null primary key generated by default as IDENTITY,
		NAME NVARCHAR(255) NOT NULL,
		created_date_tz timestamp default CURRENT_TIMESTAMP,
        modified_date_tz timestamp,
        created_user_id bigint not null,
        modified_user_id bigint,
        enabled tinyint default 1,
        deleted tinyint default 0,
        EMPLOYEE_RESPONSIBLE_ID BIGINT NULL,
        COST_CENTER_CODE NVARCHAR(255) NOT NULL,
        DESCRIPTION NVARCHAR(1000),
        SALE_ORGANIZATION_ID BIGINT NULL,
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")        
);

CREATE COLUMN TABLE "PLANNING_TOOL"."COST_CENTER_TEAMS" (
	"COST_CENTER_TEAMS_ID" BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	"COST_CENTER_ID" BIGINT NOT NULL,
	"HL3_ID" BIGINT NOT NULL,
	"CREATED_DATE_TZ" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"MODIFIED_DATE_TZ" TIMESTAMP,
	"CREATED_USER_ID" BIGINT NOT NULL,
	"MODIFIED_USER_ID" BIGINT,
	"ENABLED" TINYINT DEFAULT 1,
	"DELETED" TINYINT DEFAULT 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER" ("USER_ID"),
	FOREIGN KEY ("COST_CENTER_ID") REFERENCES "PLANNING_TOOL"."COST_CENTER" ("COST_CENTER_ID"),
	FOREIGN KEY ("HL3_ID") REFERENCES "PLANNING_TOOL"."HL3" ("HL3_ID")
);

create column table "PLANNING_TOOL"."HL6_EXPECTED_OUTCOMES" (
        "HL6_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL6_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL6_ID") REFERENCES "PLANNING_TOOL"."HL6"("HL6_ID")
);

create column table "PLANNING_TOOL"."HL6_EXPECTED_OUTCOMES_DETAIL" (
        "HL6_EXPECTED_OUTCOMES_DETAILS_ID" bigint not null primary key generated by default as IDENTITY,
        "HL6_EXPECTED_OUTCOMES_ID" bigint NOT NULL,  -- FK opt_Subprogram
        "OUTCOMES_ID" bigint NOT NULL, -- FK TAR_TARGET
        "EURO_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "VOLUME_VALUE" DECIMAL(19,2) NOT NULL DEFAULT 0,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("OUTCOMES_ID") REFERENCES "PLANNING_TOOL"."OUTCOMES"("OUTCOMES_ID"),
        FOREIGN KEY ("HL6_EXPECTED_OUTCOMES_ID") REFERENCES "PLANNING_TOOL"."HL6_EXPECTED_OUTCOMES"("HL6_EXPECTED_OUTCOMES_ID")
);



/*OBJECTIVES*/
CREATE COLUMN TABLE "PLANNING_TOOL"."OBJECTIVE" (
	OBJECTIVE_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."CAMPAIGN_TYPE" (
	CAMPAIGN_TYPE_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."CAMPAIGN_SUB_TYPE" (
	CAMPAIGN_SUB_TYPE_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

CREATE COLUMN TABLE "PLANNING_TOOL"."OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE" (
	OBJECTIVE_CAMPAIGN_TYPE_SUBTYPE_ID bigint not null primary key generated by default as IDENTITY,
	OBJECTIVE_ID BIGINT NOT NULL,
	CAMPAIGN_TYPE_ID BIGINT NOT NULL,
    CAMPAIGN_SUB_TYPE_ID BIGINT NOT NULL,
    created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
    FOREIGN KEY ("OBJECTIVE_ID") REFERENCES "PLANNING_TOOL"."OBJECTIVE"("OBJECTIVE_ID"),
    FOREIGN KEY ("CAMPAIGN_TYPE_ID") REFERENCES "PLANNING_TOOL"."CAMPAIGN_TYPE"("CAMPAIGN_TYPE_ID"),
    FOREIGN KEY ("CAMPAIGN_SUB_TYPE_ID") REFERENCES "PLANNING_TOOL"."CAMPAIGN_SUB_TYPE"("CAMPAIGN_SUB_TYPE_ID")
);
-------------------------------------------- HL6 --------------------------------------------

/********INITIALIZATION TABLES**************/

/*BEGIN HL5_STATUS_DETAIL*/

DELETE FROM HL5_STATUS_DETAIL;

insert into HL5_STATUS_DETAIL
select HL4_STATUS_DETAIL_ID, DETAIL, CURRENT_TIMESTAMP, NULL, 1, NULL, 1, 0 
from HL4_STATUS_DETAIL;
/*END BEGIN HL5_STATUS_DETAIL*/

/*BEGIN HL6_STATUS_DETAIL*/
DELETE FROM HL6_STATUS_DETAIL;

insert into HL6_STATUS_DETAIL
select HL4_STATUS_DETAIL_ID, DETAIL, CURRENT_TIMESTAMP, NULL, 1, NULL, 1, 0 
from HL4_STATUS_DETAIL;
/*END BEGIN HL6_STATUS_DETAIL*/

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT) 
VALUES('V5.0.0-05', 'Level5 & Level6 Implementation', 'V201611231400__Level5_Level6_Implementation.sql');

COMMIT;