UPDATE "PLANNING_TOOL"."PERMISSION" SET ENABLED = 0, DELETED = 1;

INSERT INTO "PLANNING_TOOL"."PERMISSION"(permission_id, name, created_user_id) VALUES(9, 'View/Read', 1);
INSERT INTO "PLANNING_TOOL"."PERMISSION"(permission_id, name, created_user_id) VALUES(10, 'Create/Edit', 1);
INSERT INTO "PLANNING_TOOL"."PERMISSION"(permission_id, name, created_user_id) VALUES(11, 'Delete', 1);

-- Updated resource names
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'Processing Report' WHERE name = 'DE Report';
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'L2', object_name = 'level2' WHERE resource_id = 1;
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'L3', object_name = 'level3' WHERE resource_id = 2;
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'L4', object_name = 'level4' WHERE resource_id = 3;
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'L5', object_name = 'level5' WHERE resource_id = 9;
UPDATE "PLANNING_TOOL"."RESOURCE" SET name = 'L6', object_name = 'level6' WHERE resource_id = 10;
INSERT INTO "PLANNING_TOOL"."RESOURCE"(name, object_name, created_user_id) VALUES('User access', 'User access', 1);

-- Delete existing role permissions
DELETE FROM "PLANNING_TOOL"."ROLE_PERMISSION";
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (1,1,1,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (9,1,2,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (17,1,3,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (25,1,4,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (33,1,5,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (41,1,6,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (49,1,7,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (57,1,8,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (3,1,1,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (11,1,2,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (19,1,3,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (27,1,4,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (35,1,5,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (43,1,6,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (51,1,7,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (59,1,8,11,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (4,1,1,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (12,1,2,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (20,1,3,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (28,1,4,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (36,1,5,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (44,1,6,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (52,1,7,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (60,1,8,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (61,1,11,9,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (62,1,11,10,1,1);
INSERT INTO "PLANNING_TOOL"."ROLE_PERMISSION" (ROLE_PERMISSION_ID, ROLE_ID, RESOURCE_ID, PERMISSION_ID, CREATED_USER_ID, ENABLED) VALUES (63,1,11,11,1,1);

-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-15', 'Changed role permissions', 'V201702011400__Changed_permissions.sql');

COMMIT;