ALTER TABLE HL5 ADD ("PRIORITY_ID" BIGINT);
ALTER TABLE HL5 ADD ("NUMBER_OF_PARTICIPANTS" NVARCHAR(255));
ALTER TABLE HL5 ADD ("REGION" NVARCHAR(255));
ALTER TABLE HL5 ADD ("EVENT_OWNER" NVARCHAR(255));

ALTER TABLE HL6 ADD ("PRIORITY_ID" BIGINT);
ALTER TABLE HL6 ADD ("NUMBER_OF_PARTICIPANTS" NVARCHAR(255));
ALTER TABLE HL6 ADD ("REGION" NVARCHAR(255));
ALTER TABLE HL6 ADD ("EVENT_OWNER" NVARCHAR(255));

CREATE COLUMN TABLE PRIORITY(
        "PRIORITY_ID" bigint not null primary key generated by default as IDENTITY,
        "NAME" NVARCHAR(255) NOT NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);

INSERT INTO PRIORITY (name, created_user_id) values ('Medium', 1);
INSERT INTO PRIORITY (name, created_user_id) values ('RDC - Online Marketing', 1);
-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-29', 'Add new fields L5 L6', 'V201703091625__Add_new_fields_L5_L6.sql');

COMMIT;

