ALTER TABLE "PLANNING_TOOL"."DISTRIBUTION_CHANNEL" ADD ("CRM_KEY" nvarchar(15));
alter table "PLANNING_TOOL"."DISTRIBUTION_CHANNEL" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "PLANNING_TOOL"."ROUTE_TO_MARKET" ADD ("CRM_KEY" nvarchar(15));
alter table "PLANNING_TOOL"."ROUTE_TO_MARKET" add (DELETED_TOKEN nvarchar(255) null);

ALTER TABLE "PLANNING_TOOL"."DISTRIBUTION_CHANNEL" ADD CONSTRAINT UK_DISTRIBUTION_CHANNEL_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."ROUTE_TO_MARKET" ADD CONSTRAINT UK_ROUTE_TO_MARKET_CRM_KEY UNIQUE(CRM_KEY, DELETED_TOKEN);

-- Update schema version
INSERT INTO "PLANNING_TOOL"."SCHEMA_VERSION"(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-63', 'Upload CRM KEY in tables', 'V201710091200__CRM_KEY.sql');


COMMIT;