create column table "PLANNING_TOOL"."ALLOCATION_CATEGORY" (
	ALLOCATION_CATEGORY_id bigint not null primary key generated by default as IDENTITY,
	measure_id bigint NULL,
	name nvarchar(60) NOT NULL,
	description nvarchar(255) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);

create column table "PLANNING_TOOL".ALLOCATION_OPTION (
	ALLOCATION_OPTION_id bigint not null primary key generated by default as IDENTITY,
	name nvarchar(255) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);

create column table "PLANNING_TOOL".ALLOCATION_CATEGORY_OPTION_LEVEL(
	ALLOCATION_CATEGORY_OPTION_LEVEL_ID BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	ALLOCATION_CATEGORY_id bigint not null,
	ALLOCATION_OPTION_id bigint not null,
	hierarchy_level_id bigint not null,
	in_processing_report tinyint null default 0,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id),
    FOREIGN KEY (ALLOCATION_CATEGORY_ID) REFERENCES "PLANNING_TOOL".ALLOCATION_CATEGORY(ALLOCATION_CATEGORY_id),
    FOREIGN KEY (ALLOCATION_OPTION_ID) REFERENCES "PLANNING_TOOL".ALLOCATION_OPTION(ALLOCATION_OPTION_id),
    FOREIGN KEY (HIERARCHY_LEVEL_ID) REFERENCES "PLANNING_TOOL".hierarchy_level(hierarchy_level_id)
);
-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-22', 'Improvement - Refactor Category and options', 'V201702081528__Refactor_Category_Option.sql');

COMMIT;