--add column needed for delete procces
alter table "PLANNING_TOOL"."HL1" add(DELETED_TOKEN nvarchar(255) null);
alter table "PLANNING_TOOL"."HL2" add(DELETED_TOKEN nvarchar(255) null);
alter table "PLANNING_TOOL"."HL3" add(DELETED_TOKEN nvarchar(255) null);
alter table "PLANNING_TOOL"."HL4" add(DELETED_TOKEN nvarchar(255) null);
alter table "PLANNING_TOOL"."HL5" add(DELETED_TOKEN nvarchar(255) null);
alter table "PLANNING_TOOL"."HL6" add(DELETED_TOKEN nvarchar(255) null);

--update column DELETED_TOKEN on deleted registres
update "PLANNING_TOOL"."HL1"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;
update "PLANNING_TOOL"."HL2"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;
update "PLANNING_TOOL"."HL3"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;
update "PLANNING_TOOL"."HL4"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;
update "PLANNING_TOOL"."HL5"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;
update "PLANNING_TOOL"."HL6"
set DELETED_TOKEN = (SELECT CAST(SYSUUID AS VARCHAR) AS "SYS_UNIQUE_NUMBER" FROM DUMMY)
where deleted = 1;

-- adding CONSTRAINT to tables
ALTER TABLE "PLANNING_TOOL"."HL1" ADD CONSTRAINT UK_HL1_CRM_ID UNIQUE(BUDGET_YEAR_ID, ACRONYM, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."HL2" ADD CONSTRAINT UK_HL2_CRM_ID UNIQUE(HL1_ID, ORGANIZATION_ACRONYM, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."HL3" ADD CONSTRAINT UK_HL3_CRM_ID UNIQUE(HL2_ID, ACRONYM, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."HL4" ADD CONSTRAINT UK_HL4_CRM_ID UNIQUE(HL3_ID, ACRONYM, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."HL5" ADD CONSTRAINT UK_HL5_CRM_ID UNIQUE(HL4_ID, ACRONYM, DELETED_TOKEN);
ALTER TABLE "PLANNING_TOOL"."HL6" ADD CONSTRAINT UK_HL6_CRM_ID UNIQUE(HL5_ID, ACRONYM, DELETED_TOKEN);


-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-59', 'Create UNIQUE constraints to levels L1 to L6', 'V201709110904__Constrains_L1toL6.sql');

COMMIT;