create column table "PLANNING_TOOL"."SERVICE_REQUEST_CATEGORY" (
	service_request_category_id bigint not null primary key generated by default as IDENTITY,
	name nvarchar(60) NOT NULL,
	description nvarchar(255) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);

create column table "PLANNING_TOOL"."SERVICE_REQUEST_OPTION" (
	service_request_option_id bigint not null primary key generated by default as IDENTITY,
	name nvarchar(255) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);

create column table "PLANNING_TOOL"."SERVICE_REQUEST_CATEGORY_OPTION_LEVEL"(
	service_request_category_option_level_id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	service_request_category_id bigint not null,
	service_request_option_id bigint not null,
	hierarchy_level_id bigint not null,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id),
    FOREIGN KEY (service_request_category_id) REFERENCES "PLANNING_TOOL".SERVICE_REQUEST_CATEGORY(SERVICE_REQUEST_CATEGORY_ID),
    FOREIGN KEY (service_request_option_id) REFERENCES "PLANNING_TOOL".SERVICE_REQUEST_OPTION(SERVICE_REQUEST_OPTION_ID),
    FOREIGN KEY (hierarchy_level_id) REFERENCES "PLANNING_TOOL".hierarchy_level(hierarchy_level_id)
);

create column table "PLANNING_TOOL"."HL5_REQUEST_CATEGORY_OPTION"(
    hl5_request_category_option_id BIGINT NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
	service_request_category_option_level_id bigint not null,
	hl5_id bigint not null,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (CREATED_USER_ID) REFERENCES "PLANNING_TOOL".USER(USER_ID),
    FOREIGN KEY (SERVICE_REQUEST_CATEGORY_OPTION_LEVEL_ID) REFERENCES "PLANNING_TOOL".SERVICE_REQUEST_CATEGORY_OPTION_LEVEL(SERVICE_REQUEST_CATEGORY_OPTION_LEVEL_ID),
    FOREIGN KEY (HL5_ID) REFERENCES "PLANNING_TOOL".HL5(HL5_ID)
);
-- *************************************************************************************
-- Update schema version
INSERT INTO SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-48', 'Service Request Category Options', 'V201707181630__Service_Request_Category_Options.sql');

COMMIT;