UPDATE "PLANNING_TOOL"."HL1" 
SET ENABLED = 0, DELETED = 1 
WHERE ACRONYM <> 'XM' AND BUDGET_YEAR_ID = 1;

UPDATE "PLANNING_TOOL"."HL2" AS HL2
SET HL2.ENABLED = 0, HL2.DELETED = 1
WHERE HL2.HL1_ID IN (SELECT HL1.HL1_ID
FROM "PLANNING_TOOL"."HL1" AS HL1
WHERE HL1.ENABLED = 0 AND
HL1.DELETED = 1);

UPDATE "PLANNING_TOOL"."HL3" AS HL3
SET HL3.ENABLED = 0, HL3.DELETED = 1
WHERE HL3.HL2_ID IN (SELECT HL2.HL2_ID
FROM "PLANNING_TOOL"."HL2" AS HL2
WHERE HL2.ENABLED = 0 AND
HL2.DELETED = 1);

UPDATE "PLANNING_TOOL"."HL4" AS HL4
SET HL4.ENABLED = 0, HL4.DELETED = 1
WHERE HL4.HL3_ID IN (SELECT HL3.HL3_ID
FROM "PLANNING_TOOL"."HL3" AS HL3
WHERE HL3.ENABLED = 0 AND
HL3.DELETED = 1);

UPDATE "PLANNING_TOOL"."HL5" AS HL5
SET HL5.ENABLED = 0, HL5.DELETED = 1
WHERE HL5.HL4_ID IN (SELECT HL4.HL4_ID
FROM "PLANNING_TOOL"."HL4" AS HL4
WHERE HL4.ENABLED = 0 AND
HL4.DELETED = 1);

UPDATE "PLANNING_TOOL"."HL6" AS HL6
SET HL6.ENABLED = 0, HL6.DELETED = 1
WHERE HL6.HL5_ID IN (SELECT HL5.HL5_ID
FROM "PLANNING_TOOL"."HL5" AS HL5
WHERE HL5.ENABLED = 0 AND
HL5.DELETED = 1);

UPDATE  "PLANNING_TOOL"."INTERLOCK_REQUEST" AS IR
SET IR.ENABLED = 0, IR.DELETED = 1
WHERE IR.HL4_ID IN (SELECT HL4.HL4_ID
FROM "PLANNING_TOOL"."HL4" AS HL4
WHERE HL4.ENABLED = 0 AND
HL4.DELETED = 1);

-- *************************************************************************************
-- Update schema version
INSERT INTO "PLANNING_TOOL".SCHEMA_VERSION(VERSION, DESCRIPTION, SCRIPT)
VALUES('V5.0.0-60', 'Disable all plans except XM', 'V201709110915__Disable_all_plans_except_XM.sql');

COMMIT;