CREATE COLUMN TABLE "PLANNING_TOOL"."INTERLOCK_CONTACT_DATA" (
		"INTERLOCK_CONTACT_DATA_ID" bigint not null primary key generated by default as IDENTITY,
        "INTERLOCK_REQUEST_ID" bigint not null,       
        "EMAIL" NVARCHAR(255) NOT NULL,
        "HASH" NVARCHAR(255) NOT NULL,
        
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,
        "SENDEMAIL"tinyint default 0,
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"), 
        FOREIGN KEY ("INTERLOCK_REQUEST_ID") REFERENCES "PLANNING_TOOL"."INTERLOCK_REQUEST"("INTERLOCK_REQUEST_ID")        
);