CREATE COLUMN TABLE "PLANNING_TOOL"."INTERLOCK_STATUS" (
        "INTERLOCK_STATUS_ID" bigint not null primary key generated by default as IDENTITY,
        "NAME" NVARCHAR(50) NOT NULL,
        "DISPLAY_NAME" NVARCHAR(50) NOT NULL,

        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);