create column table "PLANNING_TOOL".REGION (
  region_id bigint not null primary key generated by default as IDENTITY,
  region_name nvarchar(255) NOT NULL,
	region_iso nvarchar(100) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
  FOREIGN KEY (created_user_id) REFERENCES user (user_id)
);
