create column table "PLANNING_TOOL".SUBREGION (
subregion_id bigint not null primary key generated by default as IDENTITY,
subregion_name nvarchar(255) NOT NULL,
subregion_iso nvarchar(100) NULL,
region_id bigint not null,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
  FOREIGN KEY (created_user_id) REFERENCES user (user_id),
  FOREIGN KEY (region_id ) REFERENCES region(region_id )
);