create column table "PLANNING_TOOL"."HL4_EXPECTED_OUTCOMES" (
        "HL4_EXPECTED_OUTCOMES_ID" bigint not null primary key generated by default as IDENTITY,
        "HL4_ID" bigint NOT NULL,
        "COMMENTS" NVARCHAR(3000) NULL,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
        FOREIGN KEY ("HL4_ID") REFERENCES "PLANNING_TOOL"."HL4"("HL4_ID")
);