CREATE COLUMN TABLE "PLANNING_TOOL"."ROUTE_TO_MARKET" (
	ROUTE_TO_MARKET_ID bigint not null primary key generated by default as IDENTITY,
	NAME NVARCHAR(255) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
    modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);