create column table "PLANNING_TOOL".hl4_crm_binding (
	hl4_crm_binding_id bigint not null primary key generated by default as IDENTITY,
	hl4_id bigint,
	column_name nvarchar(255) NOT NULL,
	column_changed tinyint NOT NULL DEFAULT 1,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0
);