create column table "PLANNING_TOOL".spend_category (
	spend_category_id bigint not null primary key generated by default as IDENTITY,
	hierarchy_level_id bigint not null,
	name nvarchar(60) NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
	
	FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".user (user_id),
	FOREIGN KEY (hierarchy_level_id) REFERENCES "PLANNING_TOOL".hierarchy_level (hierarchy_level_id)
);