create column table "PLANNING_TOOL"."ALLOCATION_CATEGORY" (
	ALLOCATION_CATEGORY_id bigint not null primary key generated by default as IDENTITY,
	measure_id bigint NULL,
	name nvarchar(60) NOT NULL,
	description nvarchar(255) NULL,
	in_processing_report tinyint null default 0,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);