CREATE COLUMN TABLE "PLANNING_TOOL"."CV_COMPARATIVE_L4_L5_REPORT_DATA"
(
    HL4_ID INTEGER
    , HL3_ID INTEGER
    , L4_ACRONYM NVARCHAR(255)
    , L4_BUDGET DECIMAL(19,10)
    , L4_STATUS_DETAIL NVARCHAR(255)
    , CATEGORY_NAME NVARCHAR(255)
    , OPTION_NAME NVARCHAR(255)
    , L4_BUDGET_DISTRIBUTION DECIMAL(19,10)
    , L5_BUDGET_DISTRIBUTION DECIMAL(19,10)
    , DIFFERENCE DECIMAL(19,10)
    , PATH NVARCHAR(255)
    , ROW_COUNTER INTEGER
    , L4_BUDGET_PROP DECIMAL(19,10)
    , L4_BUDGET_DISTRIBUTION_PROP DECIMAL(19,10)
    , L5_BUDGET_DISTRIBUTION_PROP DECIMAL(19,10)
    , DIFFERENCE_PROP DECIMAL(19,10)
)