create column table "PLANNING_TOOL"."DICTIONARY_L5_L6" (
	DICTIONARY_L5_L6_ID bigint not null primary key generated by default as IDENTITY,
	PATH NVARCHAR(255),
	KEY_L5_L6 NVARCHAR(255),
	VALUE_L5_L6 NVARCHAR(2000),
	HIERARCHY_LEVEL_ID TINYINT,

	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);