create column table "PLANNING_TOOL".hierarchy_crm_binding (
	hierarchy_crm_binding_id bigint not null primary key generated by default as IDENTITY,
	hierarchy_level_id  bigint NOT NULL,
	column_name nvarchar(255) NOT NULL,
	table_name nvarchar(255) NOT NULL,
	order_option INTEGER NOT NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1,
	deleted tinyint default 0
);