create column table "PLANNING_TOOL".allocation_category_option_level(
	allocation_category_option_level_id BIGINT CS_FIXED GENERATED BY DEFAULT AS IDENTITY NOT NULL,
	ALLOCATION_CATEGORY_id bigint not null,
	ALLOCATION_OPTION_id bigint not null,
	hierarchy_level_id bigint not null,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id),
    FOREIGN KEY (ALLOCATION_CATEGORY_id) REFERENCES "PLANNING_TOOL".ALLOCATION_CATEGORY(ALLOCATION_CATEGORY_id),
    FOREIGN KEY (ALLOCATION_OPTION_id) REFERENCES "PLANNING_TOOL".ALLOCATION_OPTION(ALLOCATION_OPTION_id),
    FOREIGN KEY (hierarchy_level_id) REFERENCES "PLANNING_TOOL".hierarchy_level(hierarchy_level_id)
);