create column table "PLANNING_TOOL"."PARTNER"
(
        "PARTNER_ID" bigint not null PRIMARY KEY generated by default as IDENTITY,
        "PARTNER_NAME" nvarchar(512) not null,
        "PARTNER_TYPE_ID" bigint not null,
        "REGION_ID" bigint not null,
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("HIERARCHY_LEVEL_ID") REFERENCES "PLANNING_TOOL"."HIERARCHY_LEVEL"("HIERARCHY_LEVEL_ID"),
        FOREIGN KEY ("PARTNER_TYPE_ID") REFERENCES "PLANNING_TOOL"."PARTNER_TYPE"("PARTNER_TYPE_ID"),
        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);