create column table "PLANNING_TOOL"."HL4"
(
	"HL4_ID" bigint not null primary key generated by default as IDENTITY,
	"HL3_ID" bigint not null,
	"ACRONYM" nvarchar(25) not null,
	"HL4_CRM_DESCRIPTION" nvarchar(100) not null,
	--"CRM_ID" bigint not null,
	"HL4_DETAILS" nvarchar(3000) not null,
	"READ_ONLY" tinyint default 0,
	"HL4_BUSINESS_DETAILS" nvarchar(3000),
	"IS_HL4" tinyint default 1,
	"HL4_STATUS_DETAIL_ID" bigint not null,
	--"COMMENTS" nvarchar(3000),
	"HL4_PARENT_ID" bigint,
	"IS_SEND_MAIL" tinyint not null,
	"USER_ID_SEND_MAIL" bigint not null,
	
	"CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
	"MODIFIED_DATE_TZ" timestamp,
	"CREATED_USER_ID" bigint not null,
	"MODIFIED_USER_ID" bigint,
	"ENABLED" tinyint default 1,
	"DELETED" tinyint default 0,
	FOREIGN KEY ("HL3_ID") REFERENCES "PLANNING_TOOL"."HL3"("HL3_ID")
	FOREIGN KEY ("CRM_ID") REFERENCES "PLANNING_TOOL"."CRM"("CRM_ID"),
    FOREIGN KEY ("HL4_STATUS_DETAIL_ID") REFERENCES "PLANNING_TOOL"."HL4_STATUS_DETAIL"("HL4_STATUS_DETAIL_ID"),
    FOREIGN KEY ("USER_ID_SEND_MAIL") REFERENCES "PLANNING_TOOL"."USER"("USER_ID"),
    FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);