create column table "PLANNING_TOOL"."OUTCOMES_TYPE"
(
        "OUTCOMES_TYPE_ID" bigint not null PRIMARY KEY generated by default as IDENTITY,
        "OUTCOMES_TYPE_NAME" nvarchar(127),
        "CREATED_DATE_TZ" timestamp default CURRENT_TIMESTAMP,
        "MODIFIED_DATE_TZ" timestamp,
        "CREATED_USER_ID" bigint not null,
        "MODIFIED_USER_ID" bigint,
        "ENABLED" tinyint default 1,
        "DELETED" tinyint default 0,

        FOREIGN KEY ("CREATED_USER_ID") REFERENCES "PLANNING_TOOL"."USER"("USER_ID")
);