create column table "PLANNING_TOOL".ALLOCATION_OPTION (
	ALLOCATION_OPTION_id bigint not null primary key generated by default as IDENTITY,
	name nvarchar(255) NULL,
	created_date_tz timestamp default CURRENT_TIMESTAMP,
	modified_date_tz timestamp,
	created_user_id bigint not null,
	modified_user_id bigint,
	enabled tinyint default 1, 
	deleted tinyint default 0,
    FOREIGN KEY (created_user_id) REFERENCES "PLANNING_TOOL".USER(user_id)
);